//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BondShopper.ClientApp.BondShopperService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BondShopperService.IBondService")]
    public interface IBondService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBondService/GetBonds", ReplyAction="http://tempuri.org/IBondService/GetBondsResponse")]
        System.Collections.Generic.List<BondShopper.Model.Bond> GetBonds();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBondService/GetBonds", ReplyAction="http://tempuri.org/IBondService/GetBondsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BondShopper.Model.Bond>> GetBondsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBondService/GetClients", ReplyAction="http://tempuri.org/IBondService/GetClientsResponse")]
        System.Collections.Generic.List<BondShopper.Model.Client> GetClients();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBondService/GetClients", ReplyAction="http://tempuri.org/IBondService/GetClientsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BondShopper.Model.Client>> GetClientsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBondService/SubmitOrder", ReplyAction="http://tempuri.org/IBondService/SubmitOrderResponse")]
        void SubmitOrder(BondShopper.Model.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBondService/SubmitOrder", ReplyAction="http://tempuri.org/IBondService/SubmitOrderResponse")]
        System.Threading.Tasks.Task SubmitOrderAsync(BondShopper.Model.Order order);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBondServiceChannel : BondShopper.ClientApp.BondShopperService.IBondService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BondServiceClient : System.ServiceModel.ClientBase<BondShopper.ClientApp.BondShopperService.IBondService>, BondShopper.ClientApp.BondShopperService.IBondService {
        
        public BondServiceClient() {
        }
        
        public BondServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BondServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BondServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BondServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<BondShopper.Model.Bond> GetBonds() {
            return base.Channel.GetBonds();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BondShopper.Model.Bond>> GetBondsAsync() {
            return base.Channel.GetBondsAsync();
        }
        
        public System.Collections.Generic.List<BondShopper.Model.Client> GetClients() {
            return base.Channel.GetClients();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BondShopper.Model.Client>> GetClientsAsync() {
            return base.Channel.GetClientsAsync();
        }
        
        public void SubmitOrder(BondShopper.Model.Order order) {
            base.Channel.SubmitOrder(order);
        }
        
        public System.Threading.Tasks.Task SubmitOrderAsync(BondShopper.Model.Order order) {
            return base.Channel.SubmitOrderAsync(order);
        }
    }
}
